[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "constantcontact"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Vendor/Constant Contact", "Area/Marketing & Social Media", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-constantcontact"

[build-options]
observabilityIncluded = true
