// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;
import ballerina/mime;

# The Constant Contact, Inc. V3 public API, for building integrations with Constant Contact, the leading small-business email marketing platform.
public isolated client class Client {
    final http:Client clientEp;
    final readonly & ApiKeysConfig? apiKeyConfig;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.cc.email/v3") returns error? {
        http:ClientConfiguration httpClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        if config.auth is ApiKeysConfig {
            self.apiKeyConfig = (<ApiKeysConfig>config.auth).cloneReadOnly();
        } else {
            httpClientConfig.auth = <http:BearerTokenConfig|OAuth2RefreshTokenGrantConfig>config.auth;
            self.apiKeyConfig = ();
        }
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # GET User Privileges
    #
    # + headers - Headers to be sent with the request 
    # + return - The privileges granted to the user 
    remote isolated function getUserPrivileges(map<string|string[]> headers = {}) returns UserPrivilegesResource|error {
        string resourcePath = string `/account/user/privileges`;
        return self.clientEp->get(resourcePath, headers);
    }

    # GET a Summary of Account Details
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The account summary details 
    remote isolated function getAccountSummary(map<string|string[]> headers = {}, *GetAccountSummaryQueries queries) returns Customer|error {
        string resourcePath = string `/account/summary`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # PUT (update) Account Details
    #
    # + headers - Headers to be sent with the request 
    # + payload - In the request body, specify changes to account details by including and modifying all or select `CustomerPut` properties. Changes to read-only fields (`encoded_account_id`) are ignored 
    # + return - The updated account details 
    remote isolated function updateAccountSummary(CustomerPut payload, map<string|string[]> headers = {}) returns CustomerPut|error {
        string resourcePath = string `/account/summary`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # GET the Physical Address for the Account
    #
    # + headers - Headers to be sent with the request 
    # + return - The physical address for the account 
    remote isolated function getPhysicalAddress(map<string|string[]> headers = {}) returns AccountPhysicalAddress|error {
        string resourcePath = string `/account/summary/physical_address`;
        return self.clientEp->get(resourcePath, headers);
    }

    # PUT (update) the Physical Address for an Account
    #
    # + headers - Headers to be sent with the request 
    # + payload - Include all `AccountPhysicalAddress` properties required for the specified `country_code` and then update only those properties that you want to change. Excluding a non-read only field from the request body removes it from the physical address 
    # + return - The updated physical address 
    remote isolated function updatePhysicalAddress(AccountPhysicalAddress payload, map<string|string[]> headers = {}) returns AccountPhysicalAddress|error {
        string resourcePath = string `/account/summary/physical_address`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # POST the Physical Address for the Account
    #
    # + headers - Headers to be sent with the request 
    # + payload - Include all `AccountPhysicalAddress` properties required for the specified `country_code`. If a required property is not included or incorrectly formatted, a 400 error message is returned. If the address already exists, a 409 error message is returned 
    # + return - The created physical address 
    remote isolated function createPhysicalAddress(AccountPhysicalAddress payload, map<string|string[]> headers = {}) returns AccountPhysicalAddress|error {
        string resourcePath = string `/account/summary/physical_address`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # GET the Company Logo for the Account
    #
    # + headers - Headers to be sent with the request 
    # + return - The company logo for the account 
    remote isolated function getCompanyLogo(map<string|string[]> headers = {}) returns CompanyLogo|error? {
        string resourcePath = string `/account/summary/company_logo`;
        return self.clientEp->get(resourcePath, headers);
    }

    # PUT (update) the Company Logo for the Account
    #
    # + headers - Headers to be sent with the request 
    # + payload - Specify the company logo by including either `internal_id` or `external_url` 
    # + return - The updated company logo 
    remote isolated function updateCompanyLogo(CompanyLogo payload, map<string|string[]> headers = {}) returns CompanyLogo|error {
        string resourcePath = string `/account/summary/company_logo`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # GET a Collection of Account Email Addresses
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The account email addresses 
    remote isolated function listAccountEmailAddresses(map<string|string[]> headers = {}, *ListAccountEmailAddressesQueries queries) returns AccountEmails|error {
        string resourcePath = string `/account/emails`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # POST Add an Account Email Address
    #
    # + headers - Headers to be sent with the request 
    # + payload - A JSON request payload containing the new email address you want to add to the Constant Contact account 
    # + return - The added account email address 
    remote isolated function createAccountEmailAddress(AccountEmailInput payload, map<string|string[]> headers = {}) returns AccountEmailCreateResponse|error {
        string resourcePath = string `/account/emails`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # GET Activity Status Collection
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The collection of activity statuses 
    remote isolated function listActivities(map<string|string[]> headers = {}, *ListActivitiesQueries queries) returns Activities|error {
        string resourcePath = string `/activities`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET an Activity Status
    #
    # + activityId - The unique ID of the activity to GET
    # + headers - Headers to be sent with the request 
    # + return - The status of the activity 
    remote isolated function getActivity(string activityId, map<string|string[]> headers = {}) returns Activity|error {
        string resourcePath = string `/activities/${getEncodedUri(activityId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Export Contacts to a File
    #
    # + headers - Headers to be sent with the request 
    # + payload - A JSON payload that specifies the contacts (rows in the CSV file) and contact properties (columns in the CSV file) you want to export 
    # + return - The contact export activity, queued for processing 
    remote isolated function createContactsExport(ContactsExport payload, map<string|string[]> headers = {}) returns ActivityExportStatus|error {
        string resourcePath = string `/activities/contact_exports`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Retrieve Exported Contacts File
    #
    # + fileExportId - The unique ID of the exported file provided in the results: section of the export contacts activity response
    # + headers - Headers to be sent with the request 
    # + return - The exported contacts file 
    remote isolated function getContactsExport(string fileExportId, map<string|string[]> headers = {}) returns string|error {
        string resourcePath = string `/contact_exports/${getEncodedUri(fileExportId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete Contacts in Bulk
    #
    # + headers - Headers to be sent with the request 
    # + payload - The request body contains an array of contact_ids <em>or</em> list_ids. All contact_ids provided are deleted, or all members of each specified list_id are deleted 
    # + return - The bulk contact delete activity, queued for processing 
    remote isolated function createContactDeleteActivity(ContactDelete payload, map<string|string[]> headers = {}) returns ActivityDeleteStatus|error {
        string resourcePath = string `/activities/contact_delete`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Import Contacts using a CSV File
    #
    # + headers - Headers to be sent with the request 
    # + payload - CSV file and import options for bulk contact import 
    # + return - The CSV contact import activity, queued for processing 
    remote isolated function importContactsCsv(ActivitiesContactsFileImportBody payload, map<string|string[]> headers = {}) returns ActivityImport|error {
        string resourcePath = string `/activities/contacts_file_import`;
        http:Request request = new;
        mime:Entity[] bodyParts = check createBodyParts({
            "file": payload.file,
            "sms_permission_to_send": payload.smsPermissionToSend,
            "list_ids": payload.listIds
        });
        request.setBodyParts(bodyParts);
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Import Contacts using a JSON Payload
    #
    # + headers - Headers to be sent with the request 
    # + payload - The JSON request payload that contains the contact data and contact lists for the import 
    # + return - The JSON contact import activity, queued for processing 
    remote isolated function importContactsJson(ContactsJsonImport payload, map<string|string[]> headers = {}) returns ActivityImport|error {
        string resourcePath = string `/activities/contacts_json_import`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Remove Contacts from Lists
    #
    # + headers - Headers to be sent with the request 
    # + payload - The JSON payload used to create the Remove Contacts from Lists' activity 
    # + return - The remove-from-lists activity, queued for processing 
    remote isolated function createListRemoveContactsActivity(ListActivityRemoveContacts payload, map<string|string[]> headers = {}) returns ActivityListsMembership|error {
        string resourcePath = string `/activities/remove_list_memberships`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Add Contacts to Lists
    #
    # + headers - Headers to be sent with the request 
    # + payload - The JSON payload used to create the 'add contacts to lists' activity 
    # + return - The add-to-lists activity, queued for processing 
    remote isolated function createListAddContactsActivity(ListActivityAddContacts payload, map<string|string[]> headers = {}) returns ActivityListsMembership|error {
        string resourcePath = string `/activities/add_list_memberships`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete Contact Lists
    #
    # + headers - Headers to be sent with the request 
    # + payload - An array of `list_id`'s to delete 
    # + return - The list delete activity, queued for processing 
    remote isolated function createListDeleteActivity(ListIdList100 payload, map<string|string[]> headers = {}) returns ActivityDeleteListsResponse|error {
        string resourcePath = string `/activities/list_delete`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Remove Tags from Contacts
    #
    # + headers - Headers to be sent with the request 
    # + payload - The JSON payload used to create an asynchronous activity that removes tags from contacts meeting your specified contact filtering criteria 
    # + return - The tag removal activity, queued for processing 
    remote isolated function createTagRemoveContactsActivity(TagAddRemoveContacts payload, map<string|string[]> headers = {}) returns ActivityTagging|error {
        string resourcePath = string `/activities/contacts_taggings_remove`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Add Tags to Contacts
    #
    # + headers - Headers to be sent with the request 
    # + payload - The JSON payload used to create an asynchronous activity that adds tags to contacts that meet your specified contact filtering criteria 
    # + return - The tagging activity, queued for processing 
    remote isolated function createTagAddContactsActivity(TagAddRemoveContacts payload, map<string|string[]> headers = {}) returns ActivityTagging|error {
        string resourcePath = string `/activities/contacts_taggings_add`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete Tags
    #
    # + headers - Headers to be sent with the request 
    # + payload - An array of string values (`tag_id`s) to delete 
    # + return - The tag delete activity, queued for processing 
    remote isolated function createTagDeleteActivity(TagIdList500Limit payload, map<string|string[]> headers = {}) returns ActivityTagging|error {
        string resourcePath = string `/activities/contacts_tags_delete`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete Custom Fields
    #
    # + headers - Headers to be sent with the request 
    # + payload - An array of `custom_field_id`'s to delete 
    # + return - The custom field delete activity, queued for processing 
    remote isolated function createCustomFieldDeleteActivity(CustomFieldId100 payload, map<string|string[]> headers = {}) returns ActivityDeleteCustomFields|error {
        string resourcePath = string `/activities/custom_fields_delete`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # GET a collection of events.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of events 
    remote isolated function listEvents(map<string|string[]> headers = {}, *ListEventsQueries queries) returns PaginationDtoEventListingDto|error {
        string resourcePath = string `/events`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # POST (create) a new event.
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Event created successfully 
    remote isolated function createDefaultEvent(map<string|string[]> headers = {}, *CreateDefaultEventQueries queries) returns EventDto|error {
        string resourcePath = string `/events/default`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, headers);
    }

    # GET details for a single event.
    #
    # + eventId - The ID that uniquely identifies the event
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The event details 
    remote isolated function getEvent(string eventId, map<string|string[]> headers = {}, *GetEventQueries queries) returns EventDto|error {
        string resourcePath = string `/events/${getEncodedUri(eventId)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # PATCH (update) an event.
    #
    # + eventId - The ID that uniquely identifies the event to update
    # + headers - Headers to be sent with the request 
    # + payload - A JSON request body containing the event fields to update 
    # + return - Event updated successfully 
    remote isolated function updateEvent(string eventId, EventDto payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/events/${getEncodedUri(eventId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # POST (copy) an existing event.
    #
    # + eventId - The ID of the event to copy
    # + headers - Headers to be sent with the request 
    # + payload - A JSON request body containing the copy options 
    # + return - Event copied successfully 
    remote isolated function copyEvent(string eventId, EventCopyRequestDto payload, map<string|string[]> headers = {}) returns EventDto|error {
        string resourcePath = string `/events/${getEncodedUri(eventId)}/copy`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Check in event tickets.
    #
    # + eventId - The ID that uniquely identifies the event
    # + headers - Headers to be sent with the request 
    # + payload - Set of order ticket keys to mark as checked in 
    # + return - Successfully checked in order tickets 
    remote isolated function checkInTickets(string eventId, OrderTicketKeysRequestDto payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/events/${getEncodedUri(eventId)}/check_in/tickets`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Undo event ticket check-in.
    #
    # + eventId - The ID that uniquely identifies the event
    # + headers - Headers to be sent with the request 
    # + payload - Set of order ticket keys to mark as not checked in 
    # + return - Successfully undone check-in for order tickets 
    remote isolated function undoCheckInTickets(string eventId, OrderTicketKeysRequestDto payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/events/${getEncodedUri(eventId)}/undo_check_in/tickets`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get registration details for an event.
    #
    # + eventId - The ID that uniquely identifies the event
    # + trackId - The track key that uniquely identifies the event track
    # + registrationId - The ID that uniquely identifies the registration
    # + headers - Headers to be sent with the request 
    # + return - The registration details 
    remote isolated function getEventRegistration(string eventId, string trackId, string registrationId, map<string|string[]> headers = {}) returns DetailedRegistrationDto|error {
        string resourcePath = string `/events/${getEncodedUri(eventId)}/tracks/${getEncodedUri(trackId)}/registrations/${getEncodedUri(registrationId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get a list of registrations for an event.
    #
    # + eventId - The ID that uniquely identifies the event
    # + trackId - The track ID that uniquely identifies the event track
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successfully retrieved registrations 
    remote isolated function listEventRegistrations(string eventId, string trackId, map<string|string[]> headers = {}, *ListEventRegistrationsQueries queries) returns PaginatedRegistrations|error {
        string resourcePath = string `/events/${getEncodedUri(eventId)}/tracks/${getEncodedUri(trackId)}/registrations`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Update status for event registrations.
    #
    # + eventId - The ID that uniquely identifies the event
    # + trackId - The track key that uniquely identifies the event track
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Registration status update request data 
    # + return - Successfully updated registration status 
    remote isolated function updateEventRegistrationStatus(string eventId, string trackId, RegistrationStatusUpdateRequestDto payload, map<string|string[]> headers = {}, *UpdateEventRegistrationStatusQueries queries) returns error? {
        string resourcePath = string `/events/${getEncodedUri(eventId)}/tracks/${getEncodedUri(trackId)}/registrations`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Update payment status for event registrations.
    #
    # + eventId - The ID that uniquely identifies the event
    # + trackId - The track key that uniquely identifies the event track
    # + headers - Headers to be sent with the request 
    # + payload - Payment status update request data 
    # + return - Successfully updated payment status 
    remote isolated function updateEventRegistrationPaymentStatus(string eventId, string trackId, PaymentStatusUpdateRequestDto payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/events/${getEncodedUri(eventId)}/tracks/${getEncodedUri(trackId)}/registrations/payment_status`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # GET social media profiles
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The social media profiles 
    remote isolated function listSocialProfiles(map<string|string[]> headers = {}, *ListSocialProfilesQueries queries) returns Profiles|error {
        string resourcePath = string `/social/profiles`;
        map<Encoding> queryParamEncoding = {"include": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET social network connections
    #
    # + headers - Headers to be sent with the request 
    # + return - The social network connections 
    remote isolated function listSocialConnections(map<string|string[]> headers = {}) returns ConnectionResponseDto|error {
        string resourcePath = string `/social/connections`;
        return self.clientEp->get(resourcePath, headers);
    }

    # GET hashtag groups
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of hashtag groups 
    remote isolated function listSocialHashtagGroups(map<string|string[]> headers = {}, *ListSocialHashtagGroupsQueries queries) returns PagedHashtagGroupsDto|error {
        string resourcePath = string `/social/hashtags/groups`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # POST (create) a social media post
    #
    # + headers - Headers to be sent with the request 
    # + payload - The social post content and configuration 
    # + return - The created social media post 
    remote isolated function createSocialPost(PostCreateDto payload, map<string|string[]> headers = {}) returns PostDto|error {
        string resourcePath = string `/social/posts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # GET all Segments
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The collection of segments 
    remote isolated function listSegments(map<string|string[]> headers = {}, *ListSegmentsQueries queries) returns SegmentsDTO|error {
        string resourcePath = string `/segments`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # POST (create) a Segment
    #
    # + headers - Headers to be sent with the request 
    # + payload - The segment `name` and `segment_criteria` (requires single-string escaped JSON) 
    # + return - Segment successfully created 
    remote isolated function createSegment(SegmentData payload, map<string|string[]> headers = {}) returns SegmentDetail|error {
        string resourcePath = string `/segments`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # GET a Segment's Details
    #
    # + segmentId - The system-generated unique ID that identifies a segment
    # + headers - Headers to be sent with the request 
    # + return - The segment was successfully returned 
    remote isolated function getSegment(int:Signed32 segmentId, map<string|string[]> headers = {}) returns SegmentDetail|error {
        string resourcePath = string `/segments/${getEncodedUri(segmentId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # PUT (update) a Segment
    #
    # + segmentId - The system generated ID that uniquely identifies the segment that you want to modify
    # + headers - Headers to be sent with the request 
    # + payload - Include both the `name` and `segment_criteria` (single-string escaped JSON) in the body request, then make updates to either or both 
    # + return - The segment was successfully updated 
    remote isolated function updateSegment(int:Signed32 segmentId, SegmentData payload, map<string|string[]> headers = {}) returns SegmentDetail|error {
        string resourcePath = string `/segments/${getEncodedUri(segmentId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # DELETE a Segment
    #
    # + segmentId - The system generated ID that uniquely identifies the segment
    # + headers - Headers to be sent with the request 
    # + return - The segment was successfully deleted 
    remote isolated function deleteSegment(int:Signed32 segmentId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/segments/${getEncodedUri(segmentId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # PATCH (rename) a Segment
    #
    # + segmentId - The system generated ID that uniquely identifies the segment that you want to modify
    # + headers - Headers to be sent with the request 
    # + payload - Include the existing segment `name` in the body request, then rename the segment using a unique new name 
    # + return - The segment name was successfully updated 
    remote isolated function renameSegment(int:Signed32 segmentId, SegmentName payload, map<string|string[]> headers = {}) returns SegmentDetail|error {
        string resourcePath = string `/segments/${getEncodedUri(segmentId)}/name`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # GET a Contact
    #
    # + contactId - Unique ID of contact to GET
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The requested contact 
    remote isolated function getContact(string contactId, map<string|string[]> headers = {}, *GetContactQueries queries) returns ContactResource|error {
        string resourcePath = string `/contacts/${getEncodedUri(contactId)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # PUT (update) a Contact
    #
    # + contactId - Unique ID of contact to update
    # + headers - Headers to be sent with the request 
    # + payload - JSON payload defining the contact object, with updates. Any properties left blank or not included in the PUT payload are overwritten with null value - does not apply to contact subresources 
    # + return - Contact resource has been updated 
    remote isolated function updateContact(string contactId, ContactPutRequest payload, map<string|string[]> headers = {}) returns ContactResource|error {
        string resourcePath = string `/contacts/${getEncodedUri(contactId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # DELETE a Contact
    #
    # + contactId - Unique ID of contact to DELETE
    # + headers - Headers to be sent with the request 
    # + return - The contact was deleted; no content is returned 
    remote isolated function deleteContact(string contactId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/contacts/${getEncodedUri(contactId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # GET Contacts Collection
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The collection of contacts 
    remote isolated function listContacts(map<string|string[]> headers = {}, *ListContactsQueries queries) returns Contacts|error {
        string resourcePath = string `/contacts`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # POST (create) a Contact
    #
    # + headers - Headers to be sent with the request 
    # + payload - The JSON payload defining the contact 
    # + return - New contact successfully created 
    remote isolated function createContact(ContactPostRequest payload, map<string|string[]> headers = {}) returns ContactResource|error {
        string resourcePath = string `/contacts`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Create or Update a Contact
    #
    # + headers - Headers to be sent with the request 
    # + payload - A JSON request body payload that contains the contact resource you are creating or updating. The request body must contain the `email_address` property and `list_memberships` array, or the `sms_channel` object 
    # + return - Contact successfully updated 
    remote isolated function createOrUpdateContact(ContactCreateOrUpdateInput payload, map<string|string[]> headers = {}) returns ContactCreateOrUpdateResponse|error {
        string resourcePath = string `/contacts/sign_up_form`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # GET a collection of V2 and V3 API contact IDs
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The V2 to V3 contact ID cross-references 
    remote isolated function listContactIdXrefs(map<string|string[]> headers = {}, *ListContactIdXrefsQueries queries) returns ContactXrefs|error {
        string resourcePath = string `/contacts/contact_id_xrefs`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET a custom_field
    #
    # + customFieldId - The ID that uniquely identifies the custom field
    # + headers - Headers to be sent with the request 
    # + return - The requested custom field 
    remote isolated function getCustomField(string customFieldId, map<string|string[]> headers = {}) returns CustomField|error {
        string resourcePath = string `/contact_custom_fields/${getEncodedUri(customFieldId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Update a custom field.
    #
    # + customFieldId - The ID that uniquely identifies the custom field to update
    # + headers - Headers to be sent with the request 
    # + payload - The JSON payload used to update an existing custom field. Any properties omitted in the PUT request are overwritten with a null value 
    # + return - Success - custom_field updated 
    remote isolated function updateCustomField(string customFieldId, CustomFieldPutRequest payload, map<string|string[]> headers = {}) returns CustomField|error {
        string resourcePath = string `/contact_custom_fields/${getEncodedUri(customFieldId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # DELETE a custom_field
    #
    # + customFieldId - The ID that uniquely identifies the custom field to delete
    # + headers - Headers to be sent with the request 
    # + return - The custom field was deleted; no content is returned 
    remote isolated function deleteCustomField(string customFieldId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/contact_custom_fields/${getEncodedUri(customFieldId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # GET custom_fields Collection
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The collection of custom fields 
    remote isolated function listCustomFields(map<string|string[]> headers = {}, *ListCustomFieldsQueries queries) returns CustomFields|error {
        string resourcePath = string `/contact_custom_fields`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # POST (create) a custom_field
    #
    # + headers - Headers to be sent with the request 
    # + payload - The JSON payload required to create a new custom field 
    # + return - New custom field successfully created 
    remote isolated function createCustomField(CustomFieldRequest payload, map<string|string[]> headers = {}) returns CustomField|error {
        string resourcePath = string `/contact_custom_fields`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # GET a List
    #
    # + listId - The system generated ID that uniquely identifies a contact list
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The requested list 
    remote isolated function getList(string listId, map<string|string[]> headers = {}, *GetListQueries queries) returns ContactList|error {
        string resourcePath = string `/contact_lists/${getEncodedUri(listId)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # PUT (update) a List
    #
    # + listId - Unique ID of the contact list to update
    # + headers - Headers to be sent with the request 
    # + payload - JSON payload containing updates to the specified contact list 
    # + return - The updated list 
    remote isolated function updateList(string listId, ListInput payload, map<string|string[]> headers = {}) returns ContactListPutPost|error {
        string resourcePath = string `/contact_lists/${getEncodedUri(listId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # DELETE a List
    #
    # + listId - Unique ID of the list to delete
    # + headers - Headers to be sent with the request 
    # + return - Request accepted; the list delete activity status 
    remote isolated function deleteList(string listId, map<string|string[]> headers = {}) returns ActivityDeleteListResponse|error {
        string resourcePath = string `/contact_lists/${getEncodedUri(listId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # GET Lists Collection
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The collection of lists 
    remote isolated function listLists(map<string|string[]> headers = {}, *ListListsQueries queries) returns ContactListArray|error {
        string resourcePath = string `/contact_lists`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # POST (create) a List
    #
    # + headers - Headers to be sent with the request 
    # + payload - JSON payload defining the new contact list 
    # + return - New list successfully created 
    remote isolated function createList(ListInput payload, map<string|string[]> headers = {}) returns ContactListPutPost|error {
        string resourcePath = string `/contact_lists`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # GET a collection of V2 and V3 API List IDs
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The V2 to V3 list ID cross-references 
    remote isolated function listListIdXrefs(map<string|string[]> headers = {}, *ListListIdXrefsQueries queries) returns ListXrefs|error {
        string resourcePath = string `/contact_lists/list_id_xrefs`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET SMS Engagement History for a Contact
    #
    # + contactId - The contact's unique ID
    # + headers - Headers to be sent with the request 
    # + return - The SMS engagement history for the contact 
    remote isolated function getSmsEngagementHistory(string contactId, map<string|string[]> headers = {}) returns SmsEngagementHistory|error {
        string resourcePath = string `/contacts/sms_engagement_history/${getEncodedUri(contactId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # GET Contact Consent Counts
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Contact counts by consent state 
    remote isolated function getContactConsentCounts(map<string|string[]> headers = {}, *GetContactConsentCountsQueries queries) returns ContactsCounts|error {
        string resourcePath = string `/contacts/counts`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # PUT Resubscribe a Contact
    #
    # + contactId - The ID that uniquely identifies the contact to resubscribe
    # + headers - Headers to be sent with the request 
    # + payload - The JSON payload used to specify one (or more) contact lists to which the contact requested to be resubscribed 
    # + return - Contact resource has been updated 
    remote isolated function resubscribeContact(string contactId, ContactResubscribeRequest payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/contacts/resubscribe/${getEncodedUri(contactId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # GET Tag Details
    #
    # + tagId - The ID that uniquely identifies a tag (UUID format)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The requested tag 
    remote isolated function getTag(string tagId, map<string|string[]> headers = {}, *GetTagQueries queries) returns Tag|error {
        string resourcePath = string `/contact_tags/${getEncodedUri(tagId)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # PUT (Update) a Tag
    #
    # + tagId - The system generated ID used to uniquely identify the tag that you want to rename (UUID format)
    # + headers - Headers to be sent with the request 
    # + payload - The JSON payload used to update the tag name (`name`) 
    # + return - The updated tag 
    remote isolated function updateTag(string tagId, TagPut payload, map<string|string[]> headers = {}) returns Tag|error {
        string resourcePath = string `/contact_tags/${getEncodedUri(tagId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # DELETE a Tag
    #
    # + tagId - The ID that uniquely identifies a tag in UUID format
    # + headers - Headers to be sent with the request 
    # + return - The asynchronous request was successfully accepted. To view the results of the activity request, use the href link returned in the response 
    remote isolated function deleteTag(string tagId, map<string|string[]> headers = {}) returns ActivityGeneric|error {
        string resourcePath = string `/contact_tags/${getEncodedUri(tagId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # GET Details for All Tags
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The collection of tags 
    remote isolated function listTags(map<string|string[]> headers = {}, *ListTagsQueries queries) returns Tags|error {
        string resourcePath = string `/contact_tags`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # POST (Create) a Tag
    #
    # + headers - Headers to be sent with the request 
    # + payload - The JSON payload to use to create a new tag 
    # + return - The created tag 
    remote isolated function createTag(TagPost payload, map<string|string[]> headers = {}) returns Tag|error {
        string resourcePath = string `/contact_tags`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # GET a Collection of Email Campaigns
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of email campaigns 
    remote isolated function listEmailCampaigns(map<string|string[]> headers = {}, *ListEmailCampaignsQueries queries) returns PagedEmailCampaignResponse|error {
        string resourcePath = string `/emails`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # POST (Create) a New Email Campaign
    #
    # + headers - Headers to be sent with the request 
    # + payload - A JSON request body that contains the email content 
    # + return - The created email campaign. A campaign created in the legacy (V7) format is converted to the custom code format 
    remote isolated function createEmailCampaign(EmailCampaignComplete payload, map<string|string[]> headers = {}) returns EmailCampaign|error {
        string resourcePath = string `/emails`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # GET Details About a Single Email Campaign
    #
    # + campaignId - The ID (UUID format) that uniquely identifies this email campaign
    # + headers - Headers to be sent with the request 
    # + return - The requested email campaign 
    remote isolated function getEmailCampaign(string campaignId, map<string|string[]> headers = {}) returns EmailCampaign|error {
        string resourcePath = string `/emails/${getEncodedUri(campaignId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # DELETE an Email Campaign
    #
    # + campaignId - The unique ID for the email campaign you are deleting
    # + headers - Headers to be sent with the request 
    # + return - Email campaign successfully deleted. No response body returned 
    remote isolated function deleteEmailCampaign(string campaignId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/emails/${getEncodedUri(campaignId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # PATCH (Update) an Email Campaign Name
    #
    # + campaignId - The unique identifier for an email campaign
    # + headers - Headers to be sent with the request 
    # + payload - A JSON payload that contains the new email campaign name 
    # + return - The renamed email campaign 
    remote isolated function renameEmailCampaign(string campaignId, EmailCampaignName payload, map<string|string[]> headers = {}) returns EmailCampaign|error {
        string resourcePath = string `/emails/${getEncodedUri(campaignId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, headers);
    }

    # GET a Collection of V2 and V3 API Email Campaign Identifiers
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The V2 to V3 email campaign ID cross-references 
    remote isolated function listEmailCampaignIdXrefs(map<string|string[]> headers = {}, *ListEmailCampaignIdXrefsQueries queries) returns CrossReferenceResponse|error {
        string resourcePath = string `/emails/campaign_id_xrefs`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET a Single Email Campaign Activity
    #
    # + campaignActivityId - The unique ID for an email campaign activity
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The requested email campaign activity 
    remote isolated function getEmailCampaignActivity(string campaignActivityId, map<string|string[]> headers = {}, *GetEmailCampaignActivityQueries queries) returns EmailCampaignActivity|error {
        string resourcePath = string `/emails/activities/${getEncodedUri(campaignActivityId)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # PUT (Update) An Email Campaign Activity
    #
    # + campaignActivityId - The unique ID for the email campaign activity you are updating
    # + headers - Headers to be sent with the request 
    # + payload - A request body payload that contains the complete email campaign activity with your changes 
    # + return - Email campaign activity successfully updated 
    remote isolated function updateEmailCampaignActivity(string campaignActivityId, EmailCampaignActivity payload, map<string|string[]> headers = {}) returns EmailCampaignActivity|error {
        string resourcePath = string `/emails/activities/${getEncodedUri(campaignActivityId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # GET an Email Campaign Activity Schedule
    #
    # + campaignActivityId - The unique ID for an email campaign activity
    # + headers - Headers to be sent with the request 
    # + return - The schedule for the email campaign activity 
    remote isolated function listEmailSchedules(string campaignActivityId, map<string|string[]> headers = {}) returns EmailScheduleResponse|error {
        string resourcePath = string `/emails/activities/${getEncodedUri(campaignActivityId)}/schedules`;
        return self.clientEp->get(resourcePath, headers);
    }

    # POST (Create) an Email Campaign Activity Schedule
    #
    # + campaignActivityId - The unique ID for an email campaign activity. You can only schedule email campaign activities that have the `primary_email` role
    # + headers - Headers to be sent with the request 
    # + payload - A request body payload that contains the date that you want Constant Contact to send your email campaign activity on. Use `"0"` as the date to have Constant Contact immediately send the email campaign activity 
    # + return - The created schedule 
    remote isolated function createEmailSchedule(string campaignActivityId, EmailScheduleInput payload, map<string|string[]> headers = {}) returns EmailScheduleResponse|error {
        string resourcePath = string `/emails/activities/${getEncodedUri(campaignActivityId)}/schedules`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # DELETE an Email Campaign Activity Schedule
    #
    # + campaignActivityId - The unique ID for an email campaign activity
    # + headers - Headers to be sent with the request 
    # + return - Email campaign activity schedule successfully deleted. No response body returned 
    remote isolated function deleteEmailSchedules(string campaignActivityId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/emails/activities/${getEncodedUri(campaignActivityId)}/schedules`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # POST Test Send an Email Campaign Activity
    #
    # + campaignActivityId - The unique ID for an email campaign activity. You can only test send email campaign activities that have the `primary_email` role
    # + headers - Headers to be sent with the request 
    # + payload - A JSON request body that contains the recipients of the test email and an optional personal message 
    # + return - Test email campaign activity successfully sent. No response body returned 
    remote isolated function createEmailTestSend(string campaignActivityId, EmailTestSendInput payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/emails/activities/${getEncodedUri(campaignActivityId)}/tests`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # GET the HTML Preview of an Email Campaign Activity
    #
    # + campaignActivityId - The unique ID for an email campaign activity
    # + headers - Headers to be sent with the request 
    # + return - The HTML preview of the email campaign activity 
    remote isolated function getEmailCampaignActivityPreview(string campaignActivityId, map<string|string[]> headers = {}) returns EmailCampaignActivityPreview|error {
        string resourcePath = string `/emails/activities/${getEncodedUri(campaignActivityId)}/previews`;
        return self.clientEp->get(resourcePath, headers);
    }

    # GET the Send History of an Email Campaign Activity
    #
    # + campaignActivityId - The unique ID for an email campaign activity. You can return the send history for `primary_email` and `resend` role email campaign activities
    # + headers - Headers to be sent with the request 
    # + return - The send history of the email campaign activity 
    remote isolated function listEmailSendHistory(string campaignActivityId, map<string|string[]> headers = {}) returns EmailSendHistory|error {
        string resourcePath = string `/emails/activities/${getEncodedUri(campaignActivityId)}/send_history`;
        return self.clientEp->get(resourcePath, headers);
    }

    # GET Details for a Resend to Non-openers Campaign Activity
    #
    # + campaignActivityId - The unique ID for the primary email campaign activity
    # + headers - Headers to be sent with the request 
    # + return - The resend to non-openers details 
    remote isolated function getNonOpenerResend(string campaignActivityId, map<string|string[]> headers = {}) returns ResendToNonOpeners|error {
        string resourcePath = string `/emails/activities/${getEncodedUri(campaignActivityId)}/non_opener_resends`;
        return self.clientEp->get(resourcePath, headers);
    }

    # POST a Resend to Non-openers Campaign Activity
    #
    # + campaignActivityId - The unique ID for the primary email campaign activity
    # + headers - Headers to be sent with the request 
    # + payload - A JSON request body that specifies when to resend the campaign activity to non-openers 
    # + return - The created resend to non-openers activity 
    remote isolated function createNonOpenerResend(string campaignActivityId, ResendToNonOpenersInput payload, map<string|string[]> headers = {}) returns ResendToNonOpenersObject|error {
        string resourcePath = string `/emails/activities/${getEncodedUri(campaignActivityId)}/non_opener_resends`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # DELETE a Resend to Non Openers Activity
    #
    # + campaignActivityId - The unique ID for the primary email campaign activity
    # + resendRequestId - The unique ID associated with the resend for the email campaign activity (for example: `389093`). If the email campaign activity is currently in draft status, specify `DRAFT` as the ID
    # + headers - Headers to be sent with the request 
    # + return - The resend to non-openers activity was deleted; no content is returned 
    remote isolated function deleteNonOpenerResend(string campaignActivityId, string resendRequestId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/emails/activities/${getEncodedUri(campaignActivityId)}/non_opener_resends/${getEncodedUri(resendRequestId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # List All Automations
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The collection of automations 
    remote isolated function listAutomations(map<string|string[]> headers = {}, *ListAutomationsQueries queries) returns ListAutomationFlowsResponseDto|error {
        string resourcePath = string `/automations/workflows`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create an Automation
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Automation trigger definition (type, action_name, parameters, optional trigger_date and bounds) 
    # + return - The created automation 
    remote isolated function createAutomation(TriggerDefDto payload, map<string|string[]> headers = {}, *CreateAutomationQueries queries) returns AutomationCampaign|error {
        string resourcePath = string `/automations/workflows`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Retrieve an Automation
    #
    # + automationFlowId - Automation workflow identifier
    # + headers - Headers to be sent with the request 
    # + return - The requested automation 
    remote isolated function getAutomation(string automationFlowId, map<string|string[]> headers = {}) returns AutomationCampaign|error {
        string resourcePath = string `/automations/workflows/${getEncodedUri(automationFlowId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Update an Automation
    #
    # + automationFlowId - Automation workflow identifier
    # + headers - Headers to be sent with the request 
    # + payload - Automation trigger definition (type, action_name, parameters, optional trigger_date and bounds) 
    # + return - The updated automation 
    remote isolated function updateAutomation(string automationFlowId, AutomationCampaignUpdate payload, map<string|string[]> headers = {}) returns AutomationCampaign|error {
        string resourcePath = string `/automations/workflows/${getEncodedUri(automationFlowId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # GET A/B Test Details for an Email Campaign Activity
    #
    # + campaignActivityId - The unique ID for the primary email campaign activity
    # + headers - Headers to be sent with the request 
    # + return - The A/B test details 
    remote isolated function getEmailCampaignAbTest(string campaignActivityId, map<string|string[]> headers = {}) returns ABTestData|error {
        string resourcePath = string `/emails/activities/${getEncodedUri(campaignActivityId)}/abtest`;
        return self.clientEp->get(resourcePath, headers);
    }

    # POST (Create) an A/B Test for an Email Campaign Activity
    #
    # + campaignActivityId - The unique ID for the primary email campaign activity
    # + headers - Headers to be sent with the request 
    # + payload - Specify the `alternative_subject` line, `test_size` percentage of contacts (value must from `5` to `50` inclusively), and the `winner_wait_duration` (value must be `6`, `12`, `24`, or `48` hours) 
    # + return - The created A/B test 
    remote isolated function createEmailCampaignAbTest(string campaignActivityId, ABTestData payload, map<string|string[]> headers = {}) returns ABTestData|error {
        string resourcePath = string `/emails/activities/${getEncodedUri(campaignActivityId)}/abtest`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # DELETE an A/B Test for an Email Campaign Activity
    #
    # + campaignActivityId - The unique ID for the primary email campaign activity
    # + headers - Headers to be sent with the request 
    # + return - A/B test successfully deleted 
    remote isolated function deleteEmailCampaignAbTest(string campaignActivityId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/emails/activities/${getEncodedUri(campaignActivityId)}/abtest`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # GET Contact Activity Details
    #
    # + contactId - The contact's ID for which tracking activity data is requested
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Activity details for the contact 
    remote isolated function getContactTracking(string contactId, map<string|string[]> headers = {}, *GetContactTrackingQueries queries) returns ContactTrackingActivitiesPage|error {
        string resourcePath = string `/reports/contact_reports/${getEncodedUri(contactId)}/activity_details`;
        map<Encoding> queryParamEncoding = {"tracking_activity_type": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET Average Open and Click Rates
    #
    # + contactId - The contact id which is requesting tracking activity data (e.g. aa9ff7b0-478d-11e6-8059-00163e3c8e19)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The contact's average open and click rates 
    remote isolated function getContactOpenClickRate(string contactId, map<string|string[]> headers = {}, *GetContactOpenClickRateQueries queries) returns ContactOpenAndClickRates|error {
        string resourcePath = string `/reports/contact_reports/${getEncodedUri(contactId)}/open_and_click_rates`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET Contact Action Summary
    #
    # + contactId - The contact id which is requesting tracking activity data (e.g. aa9ff7b0-478d-11e6-8059-00163e3c8e19)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Summary of activity counts for the contact 
    remote isolated function getContactActivitySummary(string contactId, map<string|string[]> headers = {}, *GetContactActivitySummaryQueries queries) returns ContactCampaignActivitiesSummary|error {
        string resourcePath = string `/reports/contact_reports/${getEncodedUri(contactId)}/activity_summary`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET an Email Links Report
    #
    # + campaignActivityId - The unique ID for an email campaign activity
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The email links report 
    remote isolated function getEmailLinksReport(string campaignActivityId, map<string|string[]> headers = {}, *GetEmailLinksReportQueries queries) returns EmailLinks|error {
        string resourcePath = string `/reports/email_reports/${getEncodedUri(campaignActivityId)}/links`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET an Email Sends Report
    #
    # + campaignActivityId - The unique ID for an email campaign activity to use for this report
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of email send tracking activities 
    remote isolated function getEmailSends(string campaignActivityId, map<string|string[]> headers = {}, *GetEmailSendsQueries queries) returns SendsTrackingActivitiesPage|error {
        string resourcePath = string `/reports/email_reports/${getEncodedUri(campaignActivityId)}/tracking/sends`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET an Email Opens Report
    #
    # + campaignActivityId - The unique ID for an email campaign activity to use for this report
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of email open tracking activities 
    remote isolated function getEmailOpens(string campaignActivityId, map<string|string[]> headers = {}, *GetEmailOpensQueries queries) returns OpensTrackingActivitiesPage|error {
        string resourcePath = string `/reports/email_reports/${getEncodedUri(campaignActivityId)}/tracking/opens`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET an Email Unique Opens Report
    #
    # + campaignActivityId - The ID that uniquely identifies the email campaign activity to use for this report
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of unique email open tracking activities 
    remote isolated function getEmailUniqueOpens(string campaignActivityId, map<string|string[]> headers = {}, *GetEmailUniqueOpensQueries queries) returns OpensTrackingActivitiesPage|error {
        string resourcePath = string `/reports/email_reports/${getEncodedUri(campaignActivityId)}/tracking/unique_opens`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET an Email Did Not Opens Report
    #
    # + campaignActivityId - The ID that uniquely identifies the email campaign activity to use for this report
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of contacts who did not open the email 
    remote isolated function getEmailDidNotOpens(string campaignActivityId, map<string|string[]> headers = {}, *GetEmailDidNotOpensQueries queries) returns DidNotOpensTrackingActivitiesPage|error {
        string resourcePath = string `/reports/email_reports/${getEncodedUri(campaignActivityId)}/tracking/didnotopens`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET an Email Clicks Report
    #
    # + campaignActivityId - The ID that uniquely identifies the email campaign activity to use for this report
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of email click tracking activities 
    remote isolated function getEmailClicks(string campaignActivityId, map<string|string[]> headers = {}, *GetEmailClicksQueries queries) returns ClicksTrackingActivitiesPage|error {
        string resourcePath = string `/reports/email_reports/${getEncodedUri(campaignActivityId)}/tracking/clicks`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET an Email Forwards Report
    #
    # + campaignActivityId - The ID that uniquely identifies the email campaign activity to use for this report
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of email forward tracking activities 
    remote isolated function getEmailForwards(string campaignActivityId, map<string|string[]> headers = {}, *GetEmailForwardsQueries queries) returns ForwardsTrackingActivitiesPage|error {
        string resourcePath = string `/reports/email_reports/${getEncodedUri(campaignActivityId)}/tracking/forwards`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET an Email Opt-outs Report
    #
    # + campaignActivityId - The ID that uniquely identifies the email campaign activity to use for this report
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of email opt-out tracking activities 
    remote isolated function getEmailOptouts(string campaignActivityId, map<string|string[]> headers = {}, *GetEmailOptoutsQueries queries) returns OptoutsTrackingActivitiesPage|error {
        string resourcePath = string `/reports/email_reports/${getEncodedUri(campaignActivityId)}/tracking/optouts`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET an Email Bounces Report
    #
    # + campaignActivityId - The ID that uniquely identifies the email campaign activity to use for this report
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of email bounce tracking activities 
    remote isolated function getEmailBounces(string campaignActivityId, map<string|string[]> headers = {}, *GetEmailBouncesQueries queries) returns BouncesTrackingActivitiesPage|error {
        string resourcePath = string `/reports/email_reports/${getEncodedUri(campaignActivityId)}/tracking/bounces`;
        map<Encoding> queryParamEncoding = {"bounce_code": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET Campaign Performance Statistics
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The campaign performance statistics 
    remote isolated function getCampaignPerformanceStats(map<string|string[]> headers = {}, *GetCampaignPerformanceStatsQueries queries) returns CampaignPerformanceStatsQueryResult|error {
        string resourcePath = string `/reports/email_reports/campaign_performance`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET an Email Campaigns Summary Report
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of email campaign summaries 
    remote isolated function getEmailCampaignSummaries(map<string|string[]> headers = {}, *GetEmailCampaignSummariesQueries queries) returns BulkEmailCampaignSummariesPage|error {
        string resourcePath = string `/reports/summary_reports/email_campaign_summaries`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET an Email Campaign Stats Report
    #
    # + campaignIds - A comma-separated list of `campaign_id`s (UUID's)
    # + headers - Headers to be sent with the request 
    # + return - The statistics for the email campaigns 
    remote isolated function getEmailCampaignStats(string campaignIds, map<string|string[]> headers = {}) returns CampaignStatsQueryResultEmail|error {
        string resourcePath = string `/reports/stats/email_campaigns/${getEncodedUri(campaignIds)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # GET an Email Campaign Activity Stats Report
    #
    # + campaignActivityIds - A comma-separated list of `campaign_activity_id`s (UUID's)
    # + headers - Headers to be sent with the request 
    # + return - The statistics for the email campaign activities 
    remote isolated function getEmailCampaignActivityStats(string campaignActivityIds, map<string|string[]> headers = {}) returns CampaignActivityStatsQueryResultEmail|error {
        string resourcePath = string `/reports/stats/email_campaign_activities/${getEncodedUri(campaignActivityIds)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # GET a Unique Contacts Clicks Landing Page Report
    #
    # + campaignActivityId - The landing page `campaign_activity_id` (UUID's) to use to get unique contact click results
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of unique contact clicks on the landing page 
    remote isolated function getLandingPageUniqueContactClicks(string campaignActivityId, map<string|string[]> headers = {}, *GetLandingPageUniqueContactClicksQueries queries) returns PContactClickTrackingActivitiesPage|error {
        string resourcePath = string `/reports/landing_pages/campaign_details/${getEncodedUri(campaignActivityId)}/p_unique_contact_clicks`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET a Unique Contacts Opens Landing Page Report
    #
    # + campaignActivityId - The landing page `campaign_activity_id` (UUID's) to use to get unique contact open results
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of unique contact opens of the landing page 
    remote isolated function getLandingPageUniqueContactOpens(string campaignActivityId, map<string|string[]> headers = {}, *GetLandingPageUniqueContactOpensQueries queries) returns PContactOpensTrackingActivitiesPage|error {
        string resourcePath = string `/reports/landing_pages/campaign_details/${getEncodedUri(campaignActivityId)}/p_unique_contact_opens`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET a Contacts Opens Landing Page Report
    #
    # + campaignActivityId - The landing page `campaign_activity_id` (UUID's) to use to get unique contact open results
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of contact opens of the landing page 
    remote isolated function getLandingPageContactOpens(string campaignActivityId, map<string|string[]> headers = {}, *GetLandingPageContactOpensQueries queries) returns PContactOpensTrackingActivitiesPage|error {
        string resourcePath = string `/reports/landing_pages/campaign_details/${getEncodedUri(campaignActivityId)}/p_contact_opens`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET a Unique Contacts Updates Landing Page Report
    #
    # + campaignActivityId - The landing page `campaign_activity_id` (UUID's) to use to get unique contact open results
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of unique contact updates from the landing page 
    remote isolated function getLandingPageUniqueContactUpdates(string campaignActivityId, map<string|string[]> headers = {}, *GetLandingPageUniqueContactUpdatesQueries queries) returns PContactUpdateTrackingActivitiesPage|error {
        string resourcePath = string `/reports/landing_pages/campaign_details/${getEncodedUri(campaignActivityId)}/p_unique_contact_updates`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET a Unique Contacts Adds Landing Page Report
    #
    # + campaignActivityId - The landing page `campaign_activity_id` (UUID's) to use to get unique contact results
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of unique contacts added from the landing page 
    remote isolated function getLandingPageUniqueContactAdds(string campaignActivityId, map<string|string[]> headers = {}, *GetLandingPageUniqueContactAddsQueries queries) returns PContactAddTrackingActivitiesPage|error {
        string resourcePath = string `/reports/landing_pages/campaign_details/${getEncodedUri(campaignActivityId)}/p_unique_contact_adds`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET a Unique Contacts SMS Opt-In Landing Page Report
    #
    # + campaignActivityId - The landing page `campaign_activity_id` (UUID's) to use to get unique contact click results
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of unique contact SMS opt-ins from the landing page 
    remote isolated function getLandingPageUniqueContactSmsOptIns(string campaignActivityId, map<string|string[]> headers = {}, *GetLandingPageUniqueContactSmsOptInsQueries queries) returns PContactSMSOptInTrackingActivitiesPage|error {
        string resourcePath = string `/reports/landing_pages/campaign_details/${getEncodedUri(campaignActivityId)}/p_unique_contact_sms_optins`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET an SMS Campaigns Summary Report
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - A page of SMS campaign summaries 
    remote isolated function getSmsCampaignSummaries(map<string|string[]> headers = {}, *GetSmsCampaignSummariesQueries queries) returns SmsCampaignSummariesPage|error {
        string resourcePath = string `/reports/summary_reports/sms_campaign_summaries`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # GET Partner Client Accounts
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - The partner client accounts 
    remote isolated function listPartnerAccounts(map<string|string[]> headers = {}, *ListPartnerAccountsQueries queries) returns PartnerAccount|error {
        string resourcePath = string `/partner/accounts`;
        map<anydata> headerValues = {...headers};
        if self.apiKeyConfig is ApiKeysConfig {
            headerValues["x-api-key"] = self.apiKeyConfig?.xApiKey;
        }
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # POST (create) a Partner Client Account
    #
    # + headers - Headers to be sent with the request 
    # + payload - Create a new Constant Contact client account under your partner account. All required properties must be included in the JSON payload request 
    # + return - The provisioned client account 
    remote isolated function createPartnerAccount(Provision payload, map<string|string[]> headers = {}) returns ProvisionResponse|error {
        string resourcePath = string `/partner/accounts`;
        map<anydata> headerValues = {...headers};
        if self.apiKeyConfig is ApiKeysConfig {
            headerValues["x-api-key"] = self.apiKeyConfig?.xApiKey;
        }
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # GET Billing Plan Details for a Client Account
    #
    # + encodedAccountId - Specify the client's unique `encoded_account_id`
    # + headers - Headers to be sent with the request 
    # + return - The billing plan for the client account 
    remote isolated function getPartnerAccountPlan(string encodedAccountId, map<string|string[]> headers = {}) returns PlanTiersObject|error {
        string resourcePath = string `/partner/accounts/${getEncodedUri(encodedAccountId)}/plan`;
        map<anydata> headerValues = {...headers};
        if self.apiKeyConfig is ApiKeysConfig {
            headerValues["x-api-key"] = self.apiKeyConfig?.xApiKey;
        }
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # PUT (update) Billing Plan Details for a Client Account
    #
    # + encodedAccountId - Specify the client's unique `encoded_account_id`
    # + headers - Headers to be sent with the request 
    # + payload - `plan_type`: Updates the billing plan assigned to a client account to a different `plan_type`.    
    # + return - The updated billing plan 
    remote isolated function updatePartnerAccountPlan(string encodedAccountId, PlanInfo payload, map<string|string[]> headers = {}) returns PlanTiersObject|error {
        string resourcePath = string `/partner/accounts/${getEncodedUri(encodedAccountId)}/plan`;
        map<anydata> headerValues = {...headers};
        if self.apiKeyConfig is ApiKeysConfig {
            headerValues["x-api-key"] = self.apiKeyConfig?.xApiKey;
        }
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # PUT Cancel the Billing Plan for a Client Account
    #
    # + encodedAccountId - The system generated ID that uniquely identifies the client account
    # + headers - Headers to be sent with the request 
    # + payload - By default, the current date and time is automatically used as the cancellation date. However, you can specify a future date and time to cancel the account (`effective_date`) in the request body in ISO format. You can also enter the client's cancellation reason (`reason_id`) 
    # + return - The billing plan cancellation details 
    remote isolated function cancelPartnerAccountPlan(string encodedAccountId, AccountCancellation payload, map<string|string[]> headers = {}) returns AccountCancellation|error {
        string resourcePath = string `/partner/accounts/${getEncodedUri(encodedAccountId)}/status/cancel`;
        map<anydata> headerValues = {...headers};
        if self.apiKeyConfig is ApiKeysConfig {
            headerValues["x-api-key"] = self.apiKeyConfig?.xApiKey;
        }
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # POST Send an API request on Behalf of a Client Account
    #
    # + encodedAccountId - An encoded account id for a managed account in your partnership
    # + headers - Headers to be sent with the request 
    # + payload - A JSON request body that contains the structure of the HTTP request you are instructing Constant Contact to send on behalf of specific managed account in your partnership 
    # + return - The response to the proxied request; its schema depends on the API request sent in the body 
    remote isolated function sendPartnerAccountRequest(string encodedAccountId, PartnerAccountOperationsRequest payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/partner/accounts/${getEncodedUri(encodedAccountId)}/account_operations/sync`;
        map<anydata> headerValues = {...headers};
        if self.apiKeyConfig is ApiKeysConfig {
            headerValues["x-api-key"] = self.apiKeyConfig?.xApiKey;
        }
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # POST a User Under a Partner's SSO-Enabled Client Account
    #
    # + encodedAccountId - The encoded account ID that identifies the partner's client account to which to add the new user. 
    # + headers - Headers to be sent with the request 
    # + payload - The JSON payload used to create a new user under the specified partner's client account. All request body properties are required (`first_name`, `last_name`, `role_name`, `contact_email`, `login_name`, `external_id`, `external_provider`) 
    # + return - The SSO user was created under the client account 
    remote isolated function createPartnerSsoUser(string encodedAccountId, SSOUser payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/partner/accounts/${getEncodedUri(encodedAccountId)}/users/sso`;
        map<anydata> headerValues = {...headers};
        if self.apiKeyConfig is ApiKeysConfig {
            headerValues["x-api-key"] = self.apiKeyConfig?.xApiKey;
        }
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # POST Unsubscribe Contacts
    #
    # + encodedAccountId - The encoded account ID that uniquely identifies the partner's client account
    # + headers - Headers to be sent with the request 
    # + payload - The JSON payload 
    # + return - Contacts were successfully unsubscribed 
    remote isolated function unsubscribePartnerContacts(string encodedAccountId, ContactsUnsubscribeBody payload, map<string|string[]> headers = {}) returns PartnerUnsubscribeResponse|error {
        string resourcePath = string `/partner/accounts/${getEncodedUri(encodedAccountId)}/contacts/unsubscribe`;
        map<anydata> headerValues = {...headers};
        if self.apiKeyConfig is ApiKeysConfig {
            headerValues["x-api-key"] = self.apiKeyConfig?.xApiKey;
        }
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # GET a Collection of Webhook Topic Subscriptions
    #
    # + headers - Headers to be sent with the request 
    # + return - The webhook topic subscriptions 
    remote isolated function listWebhookSubscriptions(map<string|string[]> headers = {}) returns WebhooksSubscriptionCollection|error {
        string resourcePath = string `/partner/webhooks/subscriptions`;
        map<anydata> headerValues = {...headers};
        if self.apiKeyConfig is ApiKeysConfig {
            headerValues["x-api-key"] = self.apiKeyConfig?.xApiKey;
        }
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # GET Webhook Topic Subscription
    #
    # + topicId - Identifies a webhook topic
    # + headers - Headers to be sent with the request 
    # + return - The webhook topic subscription 
    remote isolated function getWebhookSubscription(string topicId, map<string|string[]> headers = {}) returns WebhooksSubscriptionResponse|error {
        string resourcePath = string `/partner/webhooks/subscriptions/${getEncodedUri(topicId)}`;
        map<anydata> headerValues = {...headers};
        if self.apiKeyConfig is ApiKeysConfig {
            headerValues["x-api-key"] = self.apiKeyConfig?.xApiKey;
        }
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # PUT Webhook Topic Subscription
    #
    # + topicId - Identifies a webhook topic
    # + headers - Headers to be sent with the request 
    # + payload - A JSON payload containing a callback URI. Constant Contact uses this callback URI to notify you about your chosen topic 
    # + return - The updated webhook topic subscription 
    remote isolated function updateWebhookSubscription(string topicId, WebhooksSubscriptionBody payload, map<string|string[]> headers = {}) returns WebhooksSubscriptionPutResp|error {
        string resourcePath = string `/partner/webhooks/subscriptions/${getEncodedUri(topicId)}`;
        map<anydata> headerValues = {...headers};
        if self.apiKeyConfig is ApiKeysConfig {
            headerValues["x-api-key"] = self.apiKeyConfig?.xApiKey;
        }
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # DELETE Webhook Topic Subscriptions
    #
    # + topicId - Identifies a webhook topic
    # + headers - Headers to be sent with the request 
    # + return - Webhooks subscription successfully deleted 
    remote isolated function deleteWebhookSubscription(string topicId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/partner/webhooks/subscriptions/${getEncodedUri(topicId)}`;
        map<anydata> headerValues = {...headers};
        if self.apiKeyConfig is ApiKeysConfig {
            headerValues["x-api-key"] = self.apiKeyConfig?.xApiKey;
        }
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # POST Test Send Webhook Notification
    #
    # + topicId - Identifies a webhook topic
    # + headers - Headers to be sent with the request 
    # + return - Test notification successfully sent to your callback URI 
    remote isolated function sendTestWebhook(string topicId, map<string|string[]> headers = {}) returns WebhooksTestSend|error {
        string resourcePath = string `/partner/webhooks/subscriptions/${getEncodedUri(topicId)}/tests`;
        map<anydata> headerValues = {...headers};
        if self.apiKeyConfig is ApiKeysConfig {
            headerValues["x-api-key"] = self.apiKeyConfig?.xApiKey;
        }
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }
}
